# Generated by Django 3.1.3 on 2020-11-24 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0004_auto_20201124_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='PrimaryUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyaway.customer'),
        ),
    ]
