# Generated by Django 3.1.3 on 2020-11-24 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0007_auto_20201124_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='PrimaryUser',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
