# Generated by Django 3.1.3 on 2020-11-24 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flyaway', '0010_remove_customer_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
