# Generated by Django 3.1.3 on 2020-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0013_auto_20201124_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='PrimaryUser',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
