# Generated by Django 3.1.3 on 2020-11-29 04:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0015_auto_20201124_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='flightId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flyaway.flightdetail'),
            preserve_default=False,
        ),
    ]
