# Generated by Django 3.1.3 on 2020-12-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0018_auto_20201129_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
