# Generated by Django 3.1.3 on 2021-01-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0020_auto_20201218_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='PNR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='uniquenumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flyaway.schedule'),
            preserve_default=False,
        ),
    ]
