# Generated by Django 3.1.3 on 2021-01-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0022_auto_20210126_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='refrencebooking',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
