# Generated by Django 3.1.3 on 2021-02-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0025_auto_20210126_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrencebooking',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
