# Generated by Django 3.1.3 on 2021-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0026_auto_20210201_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='transaction',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Not-Confirmed', 'Not-Confirmed'), ('Confirmed', 'Confirmed')], default='Not-Confirmed', max_length=20),
        ),
    ]
