# Generated by Django 3.1.3 on 2021-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0028_auto_20210215_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='flight_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
