# Generated by Django 3.1.3 on 2021-02-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0029_bookings_flight_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refrencebooking',
            old_name='flight_date',
            new_name='flight_time',
        ),
    ]
