# Generated by Django 3.1.3 on 2021-02-15 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0030_auto_20210215_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
