# Generated by Django 3.1.3 on 2021-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0031_bookings_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
