# Generated by Django 3.1.3 on 2021-02-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0033_auto_20210215_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
    ]
