# Generated by Django 3.1.3 on 2021-02-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0034_remove_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='verifiedOr',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=20),
        ),
    ]
