# Generated by Django 3.1.3 on 2021-02-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0036_auto_20210218_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
