# Generated by Django 3.1.3 on 2021-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0037_auto_20210218_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
