# Generated by Django 3.1.3 on 2021-02-18 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0038_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
