# Generated by Django 3.1.3 on 2021-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0039_bookings_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='farePrice',
            field=models.IntegerField(default=3520),
            preserve_default=False,
        ),
    ]
