# Generated by Django 3.1.3 on 2021-02-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0040_bookings_fareprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='farePrice',
        ),
        migrations.AddField(
            model_name='refrencebooking',
            name='price',
            field=models.CharField(default=6520, max_length=50),
            preserve_default=False,
        ),
    ]
