# Generated by Django 3.1.3 on 2021-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0041_auto_20210218_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cancellation',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='transaction',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='Not-Confirmed', max_length=20),
        ),
    ]
