# Generated by Django 3.1.3 on 2021-02-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyaway', '0042_auto_20210218_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetail',
            name='logo',
            field=models.ImageField(default=1, upload_to='company_logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='transaction',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Not-Confirmed', 'Not-Confirmed'), ('Confirmed', 'Confirmed')], default='Not-Confirmed', max_length=20),
        ),
    ]
