# Generated by Django 3.2.8 on 2021-10-23 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=web.models.Aircraft.path_and_rename)),
                ('seats', models.IntegerField()),
                ('number', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ICAO', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('IATA', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=255)),
                ('passengerFName', models.CharField(max_length=50)),
                ('passengerLName', models.CharField(max_length=50)),
                ('passengerGender', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], max_length=50)),
                ('passengerSeatNO', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Not', 'Not'), ('Confirmed', 'Confirmed')], default='Not', max_length=20)),
                ('cancellation', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=20)),
                ('pnr', models.CharField(blank=True, max_length=50, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50)),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to=web.models.Customer.rename_file)),
                ('dob', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=50)),
                ('verifiedOr', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=20)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('ScheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('fareType', models.CharField(choices=[('Partially Refundable', 'Partially Refundable'), ('Refundable', 'Refundable')], default=None, max_length=50)),
                ('farePrice', models.IntegerField()),
                ('totalSeats', models.IntegerField(default=180)),
                ('slug', models.CharField(max_length=255)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.aircraft')),
                ('where_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_from', to='web.airport')),
                ('where_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_to', to='web.airport')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
