# Generated by Django 3.2.8 on 2021-10-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211023_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(blank=True),
        ),
    ]
