# Generated by Django 3.2.8 on 2021-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_customer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
