# Generated by Django 3.2.8 on 2021-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_customer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
