# Generated by Django 3.2.8 on 2021-10-29 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_alter_schedule_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='passengerGender',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='transaction',
        ),
        migrations.CreateModel(
            name='RefBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Not', 'Not'), ('Confirmed', 'Confirmed')], default='Not', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
