# Generated by Django 3.2.8 on 2021-10-30 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20211029_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='refbooking',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 30, 3, 35, 14, 331331, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
